### ISSUE TITLE
Seed C44454144 is not beatable

### ISSUE THREAD

**Issue by Kn0p3XX** [Dessyreqt/smrandomizer#1]
This is not beatable because Morph Ball Bombs, Power Bombs or Super Missiles can't be found in possible spots.
I've gotten Screw Attack, Speed Booster, some Missiles, Grapple Beam, Morph Ball, Space Jump, Hi-Jump Boots, Reserve Tank and 1 Energy Tank.
I tried short charge just before Charge Beam, but it's too high to open it.
Log file attached.

[SM Random v20 - C44454144.sfc.spoilers.txt](https://github.com/Dessyreqt/smrandomizer/files/249689/SM.Random.v20.-.C44454144.sfc.spoilers.txt)

**Comment by Dessyreqt** [comment]
Thanks for the report! This issue appears to have affected all difficulties and will be patched in v21. I have regenerated this seed for you; only 5 items appear to have moved.


[C44454144.zip](https://github.com/Dessyreqt/smrandomizer/files/249729/C44454144.zip)

**Comment by Kn0p3XX** [comment]
Yeah, that file you send me works completely fine now. :)
