### ISSUE TITLE
Soft-lock C5698002

### ISSUE THREAD

**Issue by Nicholas-Steel** [Dessyreqt/smrandomizer#12]
If you do not have Morph Bombs and you run out of Power Bombs before entering this room, you can become soft-locked in the room as you can't escape it. You will also become stuck if you lack Morph ball ability. In order to remedy all soft-lock scenarios the vertical pillar that blocks your way back to the entrance  (to force you in to the morph ball tunnel) must be removed, I can not see any other solution that would fully resolve the issue.

https://youtu.be/reqkjkdN0H8

![untitled](https://cloud.githubusercontent.com/assets/11567846/20391981/9dff5038-ad21-11e6-9803-282f46abdbb9.png)

**Comment by moriwizz** [comment]
There are soft locks that you pretty much just have to know ahead of time and avoid. Such as the first room on the left in the green Brinstar entrance shaft where you have to kill all the enemies to exit. If you don't have morph and bombs you are stuck.
