### ISSUE TITLE
Impossible route(s)

### ISSUE THREAD

**Issue by Greedape** [Dessyreqt/smrandomizer#2]
SMRandomizer can create at least 1 impossible route (suggested order blow):

Generated Item Order
--------------------
Morphing Ball..................................Super Missile
Energy Tank (blue Brinstar)....................Screw Attack
Missile (pink Brinstar bottom).................Morphing Ball
Varia Suit.....................................Power Bomb
Missile (Hi-Jump Boots)........................Energy Tank
Energy Tank (Kraid)............................Grapple Beam
Missile (red Brinstar spike room)..............Space Jump
Missile (blue Brinstar behind missile).........Varia Suit
Missile (Gravity Suit).........................Gravity Suit
Missile (Crateria middle)......................Ice Beam
Missile (Draygon)..............................Speed Booster
Missile (Gold Torizo)..........................Charge Beam

Varia suit needs at least a single bomb or power bomb in the room righ after the hidden passageway leading to Kraid, but in this case is suggested as the source for the first bomb.

**Comment by Dessyreqt** [comment]
This will be addressed in v21
