### ISSUE TITLE
Running in Linux

### ISSUE THREAD

**Issue by ricardofiorani** [Dessyreqt/smrandomizer#3]
Any tips to run it in linux (ubuntu 16.04) ?

**Comment by kethinov** [comment]
I'm able to run it in WINE on a Mac. I bet WINE can handle it on Linux too.

**Comment by ricardofiorani** [comment]
@kethinov could you provide your Wine's version and configuration ?

**Comment by kethinov** [comment]
I used Wine 1.8, standard configuration.

**Comment by ricardofiorani** [comment]
@kethinov Thank you, I was trying on 1.7.
