### ISSUE TITLE
Is there a reason we can skip Zelda LttP's intro phase, but not SuperMet's?

### ISSUE THREAD

**Issue by TonyTheTGR** [Dessyreqt/smrandomizer#4]
I understand that the intro is standard for speedrun/races; but there's really nothing to randomize about it, and it does nothing for the player. Any chance an option to simply begin at the "escape point" could be made?

**Comment by stephini** [comment]
Hey I came here to make my own feature request and saw this and wanted to add that I like this idea too. If showing support for a feature in this way is inapropriate I'm sorry.

**Comment by TonyTheTGR** [comment]
An option in the generator might be cool, but I suspect some "speedrunner purity" is why. LttP's is pure exposition, where Super Metroid's does involve *some* gameplay.

**Comment by Dessyreqt** [comment]
You should note that the 2 minutes of text at the start of the game has been removed. Ceres IS part of the game, albeit a very easy part.
