### ISSUE TITLE
S0754952 Speedrunner difficulty Stuck in Red Brinster/Norfair

### ISSUE THREAD

**Issue by Paradox52525** [Dessyreqt/smrandomizer#40]
With this seed I ended up stuck in the the Red Brinster/Norfair area unable to climb the shaft back to Green Brinstar.  

I don't have Varia or Gravity so I cannot proceed further into Norfair and cannot even enter Maridia.  

I don't have regular bombs, ice beam, or high jump, so I cannot climb the red lower Brinstar shaft (near the Maridia tube) to get back to Green Brinstar. 

I'm aware that a "super short" (2 or 3 tap) speed boost jump can get you out of this point, but I can only do a regular short charge and there is not enough space available for that.  I believed "super short" charges were not required on speedrunner difficulty as only regular short charge is listed in the FAQ?

**Comment by moriwizz** [comment]
I think that tewtal's itemrandomizerweb fixed this by removing a few tiles on the left side of red tower so that you can wall jump up. Use that randomizer instead.

**Comment by Dessyreqt** [comment]
One of the unfortunate problems with the design of the randomizer is that it sort of doesn't mesh with the design of the game. Whereas a game like Zelda doesn't have a lot of "one-way traps" where the item you need to escape is on the other side, Super Metroid has this all over the place (starting with morph ball for a new player that doesn't even know wall jumping exists).

In this case, the red Brinstar tower is a one-way trap for both Hi-Jump and Ice Beam; in vanilla gameplay you are not expected to return until you have both items. For a speed runner, it should be sufficient to have either item. In this case, it seems both items are located in Crateria or Brinstar, and thus once you went below the rippers in the tower, you inadvertently trapped yourself. An unfortunate aspect of the design that I never got around to correcting.

In this case yous have a few choices:
1. Learn one of the toughest shinesparks in the game to get back up (not only do you have to do at least a 3 tap with a stutter, you have to do it through a door transition.)
2. If you have an earlier save, you can revert to that.
3. Failing that you can restart the seed, and don't go down to Norfair until you have either Hi-Jump or Ice Beam
4. Abandon this seed and play a different one.

This randomizer doesn't have any active plans for development at this time. Should that change, a way to mitigate one-way traps would certainly be considered as part of the design. Until then, a good alternative that is still actively developed is Total's Item Randomizer (https://itemrando.supermetroid.run/)
