### ISSUE TITLE
Issue with info page

### ISSUE THREAD

**Issue by DunsparceMeta** [Dessyreqt/smrandomizer#51]
Hey this isn't an issue with the randomizer itself but with the info page. I didn't know how else to contact the dev other than here so I'm putting this here. 

The part of the page that refers to the Zebetite Glitch links to a page that is now a virus page, and it locks you in the window. It's fairly hard to get out of and probably downloads some unwanted stuff.

Please try to fix this quickly as it seems like a real big problem.

**Comment by Dessyreqt** [comment]
This has been fixed. Sorry for the inconvenience!
