### ISSUE TITLE
How to escape Draygon's lair on masochist?

### ISSUE THREAD

**Issue by Uiraya** [Dessyreqt/smrandomizer#8]
Without gravity suit or crystal flash I'm not sure how this can be done. Every resource I've found so far indicates that you need crystal flash to spark out. Or is x-ray scope climbing required? (edit: whoops I thought CF was taken out but I just forgot about the health requirement. I'm good at this game, really. The second question is still valid, though.)

Oh while I'm here, I'm also missing two items, both in the left sand trap room (spring ball and reserve tank). Tried getting up there the first time, no good. That reserve tank might have let me beat Ridley without save scumming :o I'll get better at him later. This has been fun but I think my next game will be casual :p

**Comment by Dessyreqt** [comment]
There are quite a few ways you can do it. 

- You can spark out of Draygon's room then X-Ray climb the outside room.
- You can get CF suit, use that to get Blue Suit, then grapple glitch out of Draygon's room, then spark out of the outside room.
- You can get the CF suit then have Draygon pick you up and drop you off at the top (60 left/right to break free of his grip.) From there you can spark out. (Can't get the item that way.)

I'm sure there are more, but those are three methods off the top of my head.
